---
- name: Local install playbook
  connection: local
  hosts: localhost

  roles:
    - role: roles/common
      tags:
        - install
        - common

    - role: roles/go
      tags:
        - install
        - go

    - role: roles/neovim
      tags:
        - install
        - neovim

    - role: roles/nodejs
      tags:
        - install
        - nodejs
