---
- name: Install dependencies
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - curl
      - ca-certificates
      - gnupg
    state: present

- name: Setup the GPG keyrings directory
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory

- name: Add Nodesource apt key
  become: true
  ansible.builtin.apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
    keyring: /etc/apt/keyrings/nodesource.gpg
    state: present

- name: Add NodeSource deb repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] \
           https://deb.nodesource.com/node_{{ nodejs_major_version }}.x \
           nodistro main"
    state: present

- name: Install nodejs
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - nodejs
    state: present
