---
- name: Remove existing installation of go
  become: true
  ansible.builtin.file:
    path: /usr/local/go/
    state: absent

- name: Install go
  become: true
  ansible.builtin.unarchive:
    src: "https://golang.org/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/
    remote_src: yes

- name: Add to go binary to PATH
  ansible.builtin.lineinfile:
    path: $HOME/.profile
    line: export PATH=$PATH:/usr/local/go/bin
    insertafter: EOF
