---
- name: Update, upgrade, autoclean, and autoremove apt packages
  become: true
  ansible.builtin.apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - build-essential
      - curl
      - apt-transport-https
      - ca-certificates
      - fzf
      - ripgrep
      - bat
      - git
      - python3
      - python3-pip
    state: present

- name: Install xerox drivers
  become: true
  ansible.builtin.apt:
    deb: https://download.support.xerox.com/pub/drivers/CQ8580/drivers/linux/pt_BR/XeroxOfficev5Pkg-Linuxx86_64-5.20.661.4684.deb
