---
- name: Update, upgrade, autoclean, and autoremove apt packages
  become: true
  ansible.builtin.apt:
    upgrade: full
    update_cache: yes
    autoremove: yes
    autoclean: yes

- name: Install apt packages
  become: true
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - build-essential
      - curl
      - apt-transport-https
      - ca-certificates
      - fzf
      - ripgrep
      - bat
      - git
      - python3
      - python3-pip
    state: present
