---
- name: Download neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/\
          {{ neovim_version }}/nvim.appimage"
    dest: $HOME/.local/bin/nvim
    mode: u+x
    force: true
